### ISSUE TITLE
Why have an issue tracker for a mirror of the project?

### ISSUE THREAD

**Issue by peterjc** [jasonmc/forked-daapd#18]
As clearly stated on http://github.com/jasonmc/forked-daapd this is a mirror of the official repository which is not on github:

> Please note that this git repository is a mirror of the official one at
> git://git.debian.org/~jblache/forked-daapd.git — Read more

Given that, I would disable the issues on this github repository (and maybe the downloads too) since they distract from the official source for the project.

I'd also link to the official blog,
http://blog.technologeek.org/category/hacks/forked-daapd

**Comment by peaslaker** [comment]
Comments are closed on that blog.  You are right that there must be somewhere better than here for comments/issues.  Thanks to your prompt I am looking at reporting through debian reportbug... (which has involved installing debian in a VM) with the caveat that my target environment is not debian.

Rather than comments being closed on this mirror, a polite prompting by someone such as yourself has been sufficient in this case to point me in the right direction, which would not have happened otherwise.

**Comment by peterjc** [comment]
BTW - Sorry if my comments were too abrupt, on rereading it is a bit strong.

**Comment by ghost** [comment]
github is more user-friendly and isn't debian specific.

**Comment by peterjc** [comment]
Has anyone asked Julien Blache if he would consider using github himself? That would be a nice solution.

**Comment by peterjc** [comment]
I asked Julien Blache by email, and he would not like to switch to github or setup a bug database/issue tracker. For now forked-daapd is a small personal project, and he is happy for people to email him with bug fixes.

If Jason is happy to look at the issues filed on his mirror, then this seems like one way for forked-daapd users to give indirect feedback.

**Comment by peaslaker** [comment]
I've got an email exchange going with Julien regarding my observations and issues.  Good news is that I've identified scope for performance improvements in the database that should address one of my issues.
