### ISSUE TITLE
still a sorting problem

### ISSUE THREAD

**Issue by tomsoul** [jasonmc/forked-daapd#55]
Thank you very much for your cool software!
I switched to forked-daapd a few weeks ago beginning with version 0.15 with the sorting/library issues. Now I'm using version 0.16 and noticed that there is still a sorting problem. After rebuilding the database it looks fine but only in one way of browsing the library. In itunes you can browse from the root of the daapd tree or you can browse one level deeper "music". When using "music" the songlist isn't correct sorted. You can help yourself manually hitting the "title-number" column. The problem is bigger when you use the remote(ipad/iphone): There you can't sort anything manually. On the remote you can browse by artist->album (sorting is not correct) or you can browse directly the albums(sorting correct).
I do not use playlists and checked the mp3 tags twice.
Maybe it is best to watch my screenshots: 

http://img90.imageshack.us/img90/8548/itunes1.png
http://img714.imageshack.us/img714/3466/itunes2.png
http://img546.imageshack.us/img546/2307/remote1.png
http://img24.imageshack.us/img24/5687/remote2.png

edit: I think the album view in the remote is not correctly sorted (should numbers before alphabet characters, but not really a problem).

Thank you very much
Tom

**Comment by elwertk** [comment]
Sorting on the remote is unfinished business and some of that will come with the database performance updates in one of the next releases.

I'll have a look why and how the music playlist differs from the root type listing in terms of sorting.

K.

**Comment by elwertk** [comment]
I could repeat the itunes sorting behaviour you have observed but only on very few albums (and only on a windows version not the mac one). It however went away once and forever (even surfing itunes restart) by sorting only one of those albums by album_artist (this is how they glue this together)

Admitingly obscure but looks like an itunes hick up and not something forked daapd could influence or fix.

**Comment by tomsoul** [comment]
Thank you very much for finding time to look at this.
I have the same behavior on windows and mac(screenshots are from mac) using the latest itunes versions.
In my library are only about 10 albums, but for every album I get wrong song sortorders when browsing through "music". It's easy to fix when enable displaying the column "TitleNo" and sort manually. In my case I only use the remote and it seems that when you browse by Artist->Album it sorts like itunes->daapd-share->music.
Is there anything that I can test? Or do you need any informations that would help?

Thank you very much
Tom

edit: I just copied some more albums to the library and you are right: It´s not on every album.

**Comment by elwertk** [comment]
If you happen to have a Mac and Windows. What does happen if you share a library between them? Same behaviour?
In order to get this sorted correctly watch out for the album_artist and disk number and the various sort tags.

Remote as I said is a different story.

**Comment by tomsoul** [comment]
Hi K,
I filled out all the tags and it makes no difference. I took a look in the database and I could see when browsing the library by daap-share->music there seems to be no default sorting method: it is sorted by the ID field of the database which is maybe the listing-order when scanning the filesystem.
And it's the same order with the remote - it's the database ID (ok, sorry, remote isn't done yet :) ).

Thanks for all your time,
Tom

**Comment by elwertk** [comment]
Tom, looks like you are confusing a few things here.
The daap listings you see in itunes are really just plain unsorted song listings including all your songs. All the grouping, sorting you see are done by the client (itunes in this case). There are no queries issued if you select an album or the like. 
(all one might see is the player hooking up a song from the list for playback)
So again not something forked daapd can influence other than getting the tags pushed out correctly.

Remote is a different story and uses pre-sorted listings and triggers queries depending on requested conditions.

As said above I can no longer repeat what you are expieriencing here. Clicking on sort tags in itunes fixed it. Itunes remembers what sorting you want and even allows to sort by multiple criterias since a few versions.
Look arround the web there are many itunes tutorials to help out on that, particular if your title order is out of whack.

Hope this clarifies where to pull for achieving certain results.

K.

**Comment by tomsoul** [comment]
Hi K,
ah ok, I have though, the client triggers sql queries to get ordered lists. Thanks for clarifying.
So no bug at all, just the unfinished remote implementation!
Thanks again for all your time and please keep on developing forked-daapd!

Tom
